# Generated by Django 3.1 on 2021-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('syntax', models.CharField(max_length=30)),
                ('TinyURL', models.URLField()),
            ],
        ),
    ]
