# Generated by Django 3.1 on 2021-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteBin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
