version: '3.1'

services:
  nginx_dc:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./_nginx:/etc/nginx/conf.d
    depends_on:
      - "server_dc_http"

  server_dc_http:
    build: .
    # image: binacslee/tracy-server:github-ci
    command: hack 8000 PROD
    # ports:
    #   - 80:8000
    environment:
      - SECRET_ID=test_secreteID
      - SECRET_KEY=test_secreteKEY
    depends_on:
      - "redis_dc"
      - "mysql_dc"

  redis_dc:
    container_name: redis_dc
    image: redis
    command: --requirepass password
    # volumes:
    #   - /var/lib/redis:/data/
    # ports:
    #   - 6379:6379

  mysql_dc:
    container_name: mysql_dc
    image: mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    # volumes:
    #   - /var/lib/mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306
    #   - 33060:33060
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: password