# Generated by Django 3.1 on 2021-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TinyURL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surl', models.URLField()),
                ('tinyurl', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
